### ISSUE TITLE
Install OpenCV

### ISSUE THREAD

**Issue by ksarullo** [StetsonMathCS/snap2txt#2]
Everyone should install opencv on their computers. Leave a comment when you have done this. When everyone has installed opencv on their computers, we will close this issue.

**Comment by patelmalak** [comment]
I have opencv 3, if you have issues for the mac download homebrew, and then use the commands from the readme file

**Comment by ksarullo** [comment]
I got opencv installed and I can compile now

**Comment by kimachen** [comment]
I have opencv installed and can compile the code
